name: Check

on: [push]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu, macos]
        check: ["", toolchain]
        include:
          - runs-on: ubuntu
            make-args: CC=clang-11 CXX=clang++-11 LDFLAGS=-fuse-ld=lld ITERATIONS=50000000
          - runs-on: macos
            make-args: OFFSET=50000000 ITERATIONS=90000000
    runs-on: ${{matrix.runs-on}}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Check
        run: make ${{matrix.make-args}} CHECK=${{matrix.check}}/\* check
